#baseurl = "http://docs.kritika.io/"
baseurl = "http://docs.kritika.io/"
languageCode = "en-us"
title = "Kritika Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    # General information
    author = "kritikaio"
    description = "Service documentation"
    copyright = "Released under the MIT license"

    logo = "images/logo.png"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "brown"
        accent  = "teal"

    [params.font]
        text = "Ubuntu"
        code = "Ubuntu Mono"

[social]
    twitter = ""
    github  = "kritikaio"
    email   = "contact@kritika.io"

[[menu.main]]
    name   = "Kritika"
    url    = "/"
    weight = 0

[[menu.main]]
    name   = "Getting started"
    url    = "getting-started/"
    weight = 10

[[menu.main]]
    name   = "Roadmap"
    url    = "roadmap/"
    weight = 20

[[menu.main]]
    name   = "License"
    url    = "license/"
    weight = 30
